# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa73a529a4969b9bf65da82a712d7eb4758b0549600cc3b36dec3e643b330360ae6bf2f1c2c4673c09c645a4068b9fece3444c8bf13282eaec915720d93f439d

test:
  secret_key_base: 0bcb3682aa048a1db1edf6ebe898d7df43c1a8f0f58e422b9def973aede46f31ae1c91e3a7c75790d9be7e99abbf3d59c542026f9afc4a196c0776899a8d0097

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
